
const DIR_BINDINGS_CONFIG = 'bindings/';
const DIR_RESOURCES_CONFIG = 'resources/';
const DIR_SCHEDULES_CONFIG = 'schedules/';
const BINDING_REQUEST = 'binding-request';
const EVENT_BINDING_INITIALIZED = 'binding-initialized';
const EVENT_BINDING_ERROR = 'binding-error';
const EVENT_RESOURCE_VALUE_READING = 'resource-reading';
const BINDING_REQUEST_INIT = 'init';
const BINDING_REQUEST_PARSE_RESOURCES = 'parse-resources';
const REQUEST_READ = 'read-request';

module.exports = {
  DIR_BINDINGS_CONFIG: DIR_BINDINGS_CONFIG,
  DIR_RESOURCES_CONFIG: DIR_RESOURCES_CONFIG,
  DIR_SCHEDULES_CONFIG: DIR_SCHEDULES_CONFIG,
  BINDING_REQUEST: BINDING_REQUEST,
  EVENT_BINDING_INITIALIZED: EVENT_BINDING_INITIALIZED,
  EVENT_BINDING_ERROR: EVENT_BINDING_ERROR,
  EVENT_RESOURCE_VALUE_READING: EVENT_RESOURCE_VALUE_READING,
  BINDING_REQUEST_INIT: BINDING_REQUEST_INIT,
  BINDING_REQUEST_PARSE_RESOURCES: BINDING_REQUEST_PARSE_RESOURCES
}
